import { ActionRowBuilder, AttachmentBuilder, ButtonBuilder, ButtonStyle, Client, Message, TextChannel } from 'discord.js';
import type { ITicket, ITicketConfig } from './db';

function escHtml(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

export async function fetchAllMessages(channel: TextChannel): Promise<Message[]> {
  const all: Message[] = [];
  let before: string | undefined;
  while (true) {
    const batch = await channel.messages.fetch({ limit: 100, before });
    if (!batch.size) break;
    all.push(...batch.values());
    before = batch.last()!.id;
    if (batch.size < 100) break;
  }
  return all.sort((a, b) => a.createdTimestamp - b.createdTimestamp);
}

function buildTranscriptHtml(ticket: ITicket, messages: Message[]): string {
  const rows = messages.map(m => {
    const time = new Date(m.createdTimestamp).toUTCString();
    const avatar = m.author.displayAvatarURL({ size: 32, extension: 'png' });
    const isBot = m.author.bot ? '<span class="bot-tag">BOT</span>' : '';
    const content = escHtml(m.content || '');
    const attachments = [...m.attachments.values()]
      .map(a => a.contentType?.startsWith('image/')
        ? `<div class="attachment"><img src="${escHtml(a.url)}" alt="attachment"></div>`
        : `<div class="attachment"><a href="${escHtml(a.url)}">${escHtml(a.name ?? 'file')}</a></div>`)
      .join('');
    const embeds = m.embeds.map(e => e.description
      ? `<div class="embed">${escHtml(e.description)}</div>` : '').join('');
    return `
    <div class="msg">
      <img class="avatar" src="${avatar}" alt="">
      <div class="body">
        <span class="author">${escHtml(m.author.username)}</span>${isBot}
        <span class="ts">${time}</span>
        ${content ? `<div class="text">${content}</div>` : ''}
        ${attachments}${embeds}
      </div>
    </div>`;
  }).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Ticket #${ticket.ticket_num} Transcript</title>
<style>
  *{box-sizing:border-box;margin:0;padding:0}
  body{background:#36393f;color:#dcddde;font-family:'Segoe UI',sans-serif;padding:24px}
  .header{background:#2f3136;border-radius:8px;padding:20px 24px;margin-bottom:24px;border-left:4px solid #5865f2}
  .header h1{color:#fff;font-size:20px;margin-bottom:12px}
  .header p{color:#b9bbbe;font-size:14px;margin:3px 0}
  .msg{display:flex;padding:8px 16px;gap:16px}
  .msg:hover{background:#32353b}
  .avatar{width:40px;height:40px;border-radius:50%;flex-shrink:0;margin-top:2px}
  .body{flex:1;min-width:0}
  .author{font-weight:700;color:#fff;font-size:15px}
  .bot-tag{background:#5865f2;color:#fff;font-size:10px;padding:1px 5px;border-radius:3px;margin-left:6px;vertical-align:middle}
  .ts{color:#72767d;font-size:12px;margin-left:8px}
  .text{margin-top:4px;font-size:15px;line-height:1.4;white-space:pre-wrap;word-break:break-word}
  .attachment{margin-top:6px}.attachment img{max-width:400px;max-height:300px;border-radius:4px}
  .attachment a{color:#00aff4}
  .embed{margin-top:6px;background:#2f3136;border-left:4px solid #4f545c;padding:8px 12px;border-radius:4px;font-size:14px}
  .footer{text-align:center;color:#72767d;font-size:12px;margin-top:24px;padding-top:16px;border-top:1px solid #40444b}
</style>
</head>
<body>
<div class="header">
  <h1>🎫 Ticket #${ticket.ticket_num}</h1>
  <p><strong>Topic:</strong> ${escHtml(ticket.topic ?? 'No topic')}</p>
  <p><strong>Opened by:</strong> <@${ticket.user_id}> (ID: ${ticket.user_id})</p>
  <p><strong>Created:</strong> ${new Date((ticket as any).created_at ?? Date.now()).toUTCString()}</p>
  <p><strong>Messages:</strong> ${messages.length}</p>
</div>
${rows}
<div class="footer">Transcript generated by TMCBot • ${new Date().toUTCString()}</div>
</body>
</html>`;
}

export async function archiveTicket(
  channel: TextChannel,
  ticket: ITicket,
  cfg: ITicketConfig | null,
  bot: Client,
): Promise<void> {
  const messages = await fetchAllMessages(channel);
  const html = buildTranscriptHtml(ticket, messages);
  const file = new AttachmentBuilder(Buffer.from(html), { name: `ticket-${ticket.ticket_num}-transcript.html` });

  if (cfg?.log_channel_id) {
    try {
      const logCh = await bot.channels.fetch(cfg.log_channel_id) as TextChannel;
      await logCh.send({
        content: `📋 **Ticket #${ticket.ticket_num}** closed — <@${ticket.user_id}> — **Topic:** ${ticket.topic ?? 'None'}`,
        files: [file],
      });
    } catch {}
  }

  await channel.permissionOverwrites.delete(ticket.user_id).catch(() => {});
  await channel.setName(`closed-ticket-${ticket.ticket_num}`).catch(() => {});

  const row = new ActionRowBuilder<ButtonBuilder>().addComponents(
    new ButtonBuilder().setCustomId(`ticket:reopen:${channel.id}`).setLabel('Reopen Ticket').setStyle(ButtonStyle.Success),
    new ButtonBuilder().setCustomId(`ticket:delete:${channel.id}`).setLabel('Delete Ticket').setStyle(ButtonStyle.Danger),
  );
  await channel.send({
    content: '🔒 Ticket closed. Use the buttons below to reopen or permanently delete this ticket.',
    components: [row],
  }).catch(() => {});
}
