import {
  ActionRowBuilder, AttachmentBuilder, ButtonBuilder, ButtonInteraction, ButtonStyle,
  ChatInputCommandInteraction, Client, EmbedBuilder, Message, PermissionFlagsBits, TextChannel,
} from 'discord.js';
import type { ITicket, ITicketConfig } from './db';

function escHtml(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

export async function fetchAllMessages(channel: TextChannel): Promise<Message[]> {
  const all: Message[] = [];
  let before: string | undefined;
  while (true) {
    const batch = await channel.messages.fetch({ limit: 100, before });
    if (!batch.size) break;
    all.push(...batch.values());
    before = batch.last()!.id;
    if (batch.size < 100) break;
  }
  return all.sort((a, b) => a.createdTimestamp - b.createdTimestamp);
}

const STARS: Record<number, string> = { 1: '⭐', 2: '⭐⭐', 3: '⭐⭐⭐', 4: '⭐⭐⭐⭐', 5: '⭐⭐⭐⭐⭐' };

function buildTranscriptText(ticket: ITicket, messages: Message[], claimerName?: string): string {
  const lines: string[] = [
    `═══════════════════════════════════════`,
    `  🎫 Ticket #${ticket.ticket_num} Transcript`,
    `═══════════════════════════════════════`,
    `Topic    : ${ticket.topic ?? 'No topic'}`,
    `Opened by: ${ticket.user_id}`,
  ];
  if (claimerName) lines.push(`Claimed by: ${claimerName}`);
  lines.push(`Created  : ${new Date((ticket as any).created_at ?? Date.now()).toUTCString()}`);
  if (ticket.rating) lines.push(`Rating   : ${'⭐'.repeat(ticket.rating)} (${ticket.rating}/5)`);
  lines.push(`Messages : ${messages.length}`, `═══════════════════════════════════════`, '');

  for (const m of messages) {
    const time = new Date(m.createdTimestamp).toLocaleString('en-US', { dateStyle: 'short', timeStyle: 'short' });
    const tag = m.author.bot ? ' [BOT]' : '';
    lines.push(`[${time}] ${m.author.username}${tag}`);
    if (m.content) lines.push(m.content);
    for (const a of m.attachments.values()) lines.push(`📎 ${a.url}`);
    for (const e of m.embeds) if (e.description) lines.push(`[Embed] ${e.description.slice(0, 200)}`);
    lines.push('');
  }

  lines.push(`═══════════════════════════════════════`);
  lines.push(`Generated by TMCBot • ${new Date().toUTCString()}`);
  return lines.join('\n');
}

export function buildTranscriptFile(ticket: ITicket, messages: Message[], claimerName?: string): AttachmentBuilder {
  const text = buildTranscriptText(ticket, messages, claimerName);
  return new AttachmentBuilder(Buffer.from(text), { name: `ticket-${ticket.ticket_num}-transcript.txt` });
}

export async function archiveTicket(
  channel: TextChannel,
  ticket: ITicket,
  cfg: ITicketConfig | null,
  bot: Client,
): Promise<void> {
  // Fetch messages and generate transcript
  const messages = await fetchAllMessages(channel);

  let claimerName: string | undefined;
  if (ticket.claimed_by) {
    const claimer = await bot.users.fetch(ticket.claimed_by).catch(() => null);
    claimerName = claimer?.username;
  }

  const file = buildTranscriptFile(ticket, messages, claimerName);

  // Post transcript to log channel
  if (cfg?.log_channel_id) {
    try {
      const logCh = await bot.channels.fetch(cfg.log_channel_id) as TextChannel;
      const ratingText = ticket.rating ? ` • Rating: ${STARS[ticket.rating]}` : '';
      const claimerText = claimerName ? ` • Claimed by: ${claimerName}` : '';
      await logCh.send({
        content: `📋 **Ticket #${ticket.ticket_num}** closed — <@${ticket.user_id}> — **Topic:** ${ticket.topic ?? 'None'}${claimerText}${ratingText}`,
        files: [file],
      });
    } catch {}
  }

  // Post rating panel in the ticket channel before it gets deleted
  try {
    const helperText = claimerName
      ? `How was your experience with **${claimerName}**?`
      : 'How was your support experience?';
    const ratingRow = new ActionRowBuilder<ButtonBuilder>().addComponents(
      ...[1, 2, 3, 4, 5].map(n =>
        new ButtonBuilder()
          .setCustomId(`ticket:rate:${n}:${channel.id}`)
          .setLabel(`${n} ⭐`)
          .setStyle(ButtonStyle.Secondary)
      )
    );
    const embed = new EmbedBuilder()
      .setColor(0x5865F2)
      .setTitle('🔒 Ticket Closed')
      .setDescription(`${helperText}\n\n*This channel will be deleted in 2 minutes.*`);
    await channel.send({ content: `<@${ticket.user_id}>`, embeds: [embed], components: [ratingRow] });
  } catch {}

  // Delete channel after 2 minutes
  setTimeout(() => channel.delete().catch(() => {}), 2 * 60 * 1000);
}

export function buildModPanel(channelId: string): ActionRowBuilder<ButtonBuilder>[] {
  const row1 = new ActionRowBuilder<ButtonBuilder>().addComponents(
    new ButtonBuilder().setCustomId(`ticket:claim:${channelId}`).setLabel('🙋 Claim').setStyle(ButtonStyle.Primary),
  );
  const row2 = new ActionRowBuilder<ButtonBuilder>().addComponents(
    new ButtonBuilder().setCustomId(`ticket:save:${channelId}`).setLabel('💾 Save Transcript').setStyle(ButtonStyle.Secondary),
    new ButtonBuilder().setCustomId(`ticket:close:${channelId}`).setLabel('🔒 Close').setStyle(ButtonStyle.Danger),
  );
  return [row1, row2];
}

// ─── Ticket permissions ───────────────────────────────────────────────────────

type TicketInteraction = ButtonInteraction | ChatInputCommandInteraction;

/** Server admins. `has()` resolves Administrator implicitly, so Manage Server covers both. */
export function isTicketAdmin(interaction: TicketInteraction): boolean {
  return interaction.memberPermissions?.has(PermissionFlagsBits.ManageGuild) ?? false;
}

function memberRoleIds(interaction: TicketInteraction): string[] {
  const member: any = interaction.member;
  if (!member) return [];
  if (Array.isArray(member.roles)) return member.roles;
  return [...(member.roles?.cache?.keys() ?? [])];
}

/** Admins, the configured support role, or anyone with Manage Messages when no support role is set. */
export function isTicketStaff(interaction: TicketInteraction, cfg: ITicketConfig | null): boolean {
  if (isTicketAdmin(interaction)) return true;
  if (cfg?.support_role_id) return memberRoleIds(interaction).includes(cfg.support_role_id);
  return interaction.memberPermissions?.has(PermissionFlagsBits.ManageMessages) ?? false;
}

export type TicketPermCheck = { allowed: true } | { allowed: false; reason: string };

/**
 * Only admins and the staff member who claimed the ticket may close it.
 * The person who opened the ticket never can, even if they otherwise qualify.
 */
export function canCloseTicket(interaction: TicketInteraction, ticket: ITicket): TicketPermCheck {
  if (ticket.user_id === interaction.user.id) {
    return {
      allowed: false,
      reason: '❌ You opened this ticket, so you can\'t close it. A staff member who claims it — or an admin — will close it for you.',
    };
  }
  if (isTicketAdmin(interaction)) return { allowed: true };
  if (ticket.claimed_by && ticket.claimed_by === interaction.user.id) return { allowed: true };
  return { allowed: false, reason: '❌ Only an admin or the staff member who claimed this ticket can close it.' };
}
